typo3:
  build: .
  links: 
   - db
  ports:
   - "80:8080"
  environment:
    DB_NAME: typo3
    DB_USER: admin
    DB_PASS: "dockymocky"
    DB_HOST: "db"
    DB_PORT: "3306"
db:
  image: million12/mariadb
  environment:
    MARIADB_PASS: "my-pass"
